#!/usr/bin/env python3
"""Generate documentation page from screenshots and feature descriptions.

This script produces ``docs/visualization_guide.md`` with embedded
screenshot references and a feature overview.  It is called by the
``generate-docs`` GitHub Actions workflow after screenshots have been
captured.

Usage
-----
    python3 scripts/generate_docs.py
"""

import os
from datetime import datetime, timezone


DOCS_DIR = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "docs")
SCREENSHOTS_DIR = os.path.join(DOCS_DIR, "screenshots")
OUTPUT_PATH = os.path.join(DOCS_DIR, "visualization_guide.md")


def main():
    os.makedirs(DOCS_DIR, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Discover available screenshots
    screenshots = []
    if os.path.isdir(SCREENSHOTS_DIR):
        screenshots = sorted(
            f for f in os.listdir(SCREENSHOTS_DIR)
            if f.endswith(".png")
        )

    with open(OUTPUT_PATH, "w") as f:
        f.write("# Long Read Visualization — User Guide\n\n")
        f.write(f"> Auto-generated on {timestamp}\n\n")

        f.write("## Overview\n\n")
        f.write(
            "The multi-panel IGV.js visualization server displays long-read\n"
            "sequencing data across three coordinated panels: **Reference**,\n"
            "**Haplotype 1**, and **Haplotype 2**.  The server supports both\n"
            "BAM and CRAM read formats.\n\n"
        )

        f.write("## Features\n\n")
        f.write(
            "| Feature | Description |\n"
            "|---------|-------------|\n"
            "| **Three coordinated panels** | Reference, Haplotype 1, and "
            "Haplotype 2 each have their own IGV.js browser instance |\n"
            "| **Synchronized navigation** | Navigate in the reference panel "
            "and both assembly panels follow via coordinate translation |\n"
            "| **Region-of-interest browsing** | Step through SV regions with "
            "◀/▶ buttons or keyboard shortcuts |\n"
            "| **BAM & CRAM support** | Reads can be loaded from BAM or CRAM "
            "files; CRAM files use the panel reference for decoding |\n"
            "| **Long-read display mode** | Spurious small indels are hidden "
            "by default (threshold ≤ 3 bp), matching Java IGV behavior |\n"
            "| **Squished display** | Reads default to squished (compact) "
            "view for better overview; toggle to expanded with one click |\n"
            "| **Byte-range HTTP** | Full support for HTTP Range requests "
            "enabling efficient BAM/CRAM random access |\n"
            "| **Containerized** | Run via Apptainer/Docker with the same "
            "image used for the pipeline |\n"
        )

        f.write("\n## Display Controls\n\n")
        f.write(
            "The toolbar provides quick-access toggle buttons:\n\n"
            "- **☰ Squished / ≡ Expanded** — Switch between compact and "
            "full-height read display\n"
            "- **🧹 Hide indels / 🔍 Show indels** — Toggle suppression of "
            "spurious small indels (≤ 3 bp)\n"
            "- **Sync panels** — Enable/disable cross-panel coordinate "
            "synchronization\n\n"
        )

        f.write("## Keyboard Shortcuts\n\n")
        f.write(
            "| Key | Action |\n"
            "|-----|--------|\n"
            "| `←` or `[` | Previous region |\n"
            "| `→` or `]` | Next region |\n"
        )

        if screenshots:
            f.write("\n## Screenshots\n\n")
            for img in screenshots:
                # Convert filename to a title: 01_main_view.png → Main view
                title = img.rsplit(".", 1)[0]       # remove extension
                title = title.split("_", 1)[-1]     # remove numeric prefix
                title = title.replace("_", " ").capitalize()
                f.write(f"### {title}\n\n")
                f.write(f"![{title}](screenshots/{img})\n\n")
        else:
            f.write("\n## Screenshots\n\n")
            f.write(
                "*Screenshots are generated automatically by the "
                "`generate-docs` CI workflow.*\n\n"
            )

        f.write("---\n\n")
        f.write(
            "*This document is auto-generated by "
            "`scripts/generate_docs.py`.*\n"
        )

    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
